### ISSUE TITLE
Does not output anything on Windows (no files generated)

### ISSUE THREAD

**Issue by fortinmike** [whs/piped-webpack#2] opened 2017-08-04 17:27 UTC
Our project must be buildable on both *nix and Windows. However I just noticed that `piped-webpack` outputs nothing on Windows while it works fine on `macOS`. No files are generated, but the usual webpack logging seems to indicate that compilation was performed successfully. Is there something I can do to fix this? How can I diagnose what's happening?

Running my webpack config using the `webpack` command directly generates files as expected.

Here is my webpack output when run by gulp:

```
Version: webpack 3.4.1
Time: 4460ms
     Asset     Size  Chunks                    Chunk Names
lib.dll.js  9.25 MB       0  [emitted]  [big]  lib
   [0] ./node_modules/process/browser.js 5.42 kB {0} [built]
   [1] ./node_modules/react/react.js 56 bytes {0} [built]
...
  [17] ./node_modules/react-redux/lib/index.js 475 bytes {0} [built]
  [98] ./node_modules/redux/es/index.js 1.08 kB {0} [built]
 [123] ./node_modules/react-dom/index.js 59 bytes {0} [built]
 [140] ./node_modules/react-router/es/index.js 1.46 kB {0} [built]
 [342] dll lib 12 bytes {0} [built]
...
    + 824 hidden modules
[13:23:49] Finished '_scripts_lib' after 4.7 s
```

Here is my gulp task:

```
gulp.task("_scripts_lib", function () {
  return gulp.src([])
    .pipe(pipedWebpack(require("./webpack.lib.config.js")))
    .pipe(gulp.dest(SCRIPTS_OUTPUT_DIR));
});
```

and here is my webpack config file:

```
/* global __dirname process */

let path = require("path");
let Webpack = require("webpack");

const libName = "[name]_[hash]";

let config = {
  resolve: {
    modules: [
      __dirname,
      "node_modules"
    ],
    extensions: [".js", ".jsx"]
  },
  entry: {
    lib: [
      "react",
      "react-dom",
      "react-router",
      "redux",
      "react-redux"
    ]
  },
  module: {
    rules: [
      // Process JS(X) files using Babel
      { test: /\.jsx?$/, loader: "babel-loader", include: [/scripts/], query: { presets: ["react", "es2015"] } },
    ]
  },
  plugins: [
    new Webpack.DllPlugin({
      name: libName,
      path: path.join(__dirname, "[name].dll-manifest.json")
    })
  ],
  output: {
    filename: "[name].dll.js",
    library: libName
  }
};

module.exports = config;

```

**Comment by whs** [comment] 2017-08-05 00:37
I believe the problem is that MemoryFsStream doesn't support Windows.

Here's where I believe the problem to be:

- Usually if no output path is configured, Webpack will output to current directory
- And so in lib/memoryFsStream.js, it starts looking from process.cwd() so you could pipe the output anywhere without having your filesystem as prefix This is done in the _read method
- However, I'm not sure how that Windows-like path is organized in MemoryFs, as they have a drive prefix.

I don't have my development environment setup in Windows, so I'd welcome if you could submit a PR.

**Comment by fortinmike** [comment] 2017-08-07 14:26
I might try to do it, but I'd need a bit more pointers.

How can I setup a dev environment to debug this and try it in my Gulp build process? Any way I can step into the plugin's code with a debugger while it runs?

**Comment by whs** [comment] 2017-08-07 14:38
- To modify this plugin, clone this repository and run [`npm link`](https://docs.npmjs.com/cli/link). After that, go to your project directory (the one that is using this plugin) and run `npm link piped-webpack`. It will now use your copy of the plugin instead of installing it from npm.
- I usually debug by throwing `console.log` around my code (I recommend adding some in `memoryFsStream`) but if you do need debugger, here's how [Node debugger](https://nodejs.org/api/debugger.html) can be used
  1. Add a `debugger` statement somewhere in your code. Can be in this plugin, or in your gulpfile. This statement is a breakpoint; when Node hit this statement it will pause.
  2. Open Chrome/Chromium and go to `chrome://inspect/`. Click the blue "Open dedicated DevTools for Node"
  3. Run `node --inspect node_modules/.bin/gulp your_normal_gulp_arguments_here`. You can also use `--inspect-brk` where it will pause immediately.
  4. When Node hit your debugger statement, your Chrome development tool will popup. Now you can use it just like normal web inspector. It is worth nothing that the Chrome console will also be Node's REPL so you can also require() node modules.

**Comment by fortinmike** [comment] 2017-08-07 21:30
Great, thanks for the info! I should have some time to take a look at this soon.

**Comment by fortinmike** [comment] 2017-08-07 21:30
Great, thanks for the info! I should take a look at this soon.

**Comment by whs** [comment] 2017-08-09 13:25
I just pushed a fix. Could you please test from master?

**Comment by fortinmike** [comment] 2017-08-09 14:32
It works! 🥇 Thanks for taking the time to fix this. Please let me know when this is published on npm, we'll begin using it right away.

**Comment by whs** [comment] 2017-08-09 14:59
I'll publish a new release on npm tomorrow

**Closed as completed by whs** 2017-08-09 14:59 UTC

**Comment by whs** [comment] 2017-08-10 14:08
Version 1.2.0 is now on npm

**Comment by fortinmike** [comment] 2017-08-10 15:22
You sir, are awesome. Thanks a lot for the fix! 👍
